-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'e9bbca3338387476' HASH 'fe96d7b28704b3606e6ab5a413de2a1bff335abd71a75014526d217df791d91a' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 47) NOT NULL,
    "USERNAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "EMAIL" CHARACTER VARYING(255),
    "CPF" CHARACTER VARYING(255),
    "AGE" CHARACTER VARYING(3),
    "ADDRESS" CHARACTER VARYING(255),
    "CEP" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 38 +/- SELECT COUNT(*) FROM PUBLIC.USERS;  
INSERT INTO "PUBLIC"."USERS" VALUES
(1, 'rafael', '123', 'rua arnaldo 160', '25', NULL, '4444222', 'rafa_1310@icloud.com'),
(8, 'rafael', '123', NULL, NULL, NULL, '4444222', 'rafa_1310@icloud.com'),
(9, 'rafael', '123', NULL, NULL, NULL, '4444222', 'rafa_1310@icloud.com'),
(10, 'rafael', '123', 'rua arnaldo', '12', NULL, '4444222', 'rafa_1310@icloud.com'),
(13, 'ricardo', '20', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', NULL),
(14, 'ricardo', '123', '2222', '2222', '12', 'rua arnaldo', NULL),
(15, 'rafael', '123', 'rafa_1310@icloud.com', '2222', '12', 'rua arnaldo', '1222'),
(16, 'rafael', '123', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', '1222'),
(17, 'rafael', '123', '2222', '2222', '12', 'rua arnaldo', 'dddddd'),
(18, 'rafael', '123', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', 'dddddd'),
(19, 'ricardo', '20', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', 'dddddd'),
(20, 'ricardo', '20', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', '1222'),
(21, 'rafael', '123', '2222', '4444222', '12', 'rua arnaldo', '1222'),
(22, 'r', '123', '2222', '2222', '12', 'rua arnaldo', '12'),
(23, 'eeee', 'eeee', 'eee', 'eee', 'eee', 'eee', 'eeee'),
(24, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(25, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(26, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(27, 'rafael', '123', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', 'dddddd'),
(28, 'rafael', '123', 'rafa_1310@icloud.com', '2222', '12', 'rua arnaldo', '1222'),
(29, 'rafael', '20', '2222', '2222', 'eee', 'eee', '1222'),
(30, 'ricardo', '20', '111', '4444222', '12', 'rua arnaldo', '1222'),
(31, 'tw', 'aa', 'rafa_1310@icloud.com', '2222', 'eee', 'rua arnaldo', '1222'),
(32, 'rafael', '123', '2222', '2222', '12', 'rua arnaldo', 'dddddd'),
(33, 'ricardinho', '20', '2222', '4444222', '12', 'rua arnaldo', 'dddddd'),
(34, 'rafael', '123', '2222', '2222', '12', 'rua arnaldo', '1222'),
(35, 'ricardinho', '1233', '2222', '2222', '12', 'eee', '1222'),
(36, 'rafael', '1233', '2222', '2222', 'eee', 'rua arnaldo', '1222'),
(37, 'rafael', '20', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', '1222'),
(38, 'rafael', '123', '2222', '4444222', '12', 'rua arnaldo', 'dddddd'),
(39, 'rafael', '123', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', '1222'),
(40, 'marilia ', '222', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', '1222'),
(41, 'ricardinho', '20', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', 'dddddd'),
(42, 'rafael', '20', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', '1222'),
(43, 'rafael', '123', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', 'dddddd'),
(44, 'rafael', '20', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', '1222'),
(45, 'rafael', '22222', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', '1222'),
(46, 'rafael', '123', 'rafa_1310@icloud.com', '4444222', '12', 'rua arnaldo', '1222');      
CREATE CACHED TABLE "PUBLIC"."PET"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 43) NOT NULL,
    "NAME" CHARACTER VARYING(255),
    "TYPE" CHARACTER VARYING(255),
    "BREED" CHARACTER VARYING(255),
    "SIZE" CHARACTER VARYING(255),
    "GENDER" CHARACTER VARYING(255),
    "AGE" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING(255),
    "IMAGE" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."PET" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");          
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.PET;     
INSERT INTO "PUBLIC"."PET" VALUES
(1, 'Laguna', 'peixe', NULL, 'pequeno', 'masculino', '2 anos', NULL, NULL),
(4, 'Moluscooooo', 'peixe', 'nao sei', 'pequeno', 'masculino', '2 anos', 'teste', NULL),
(5, 'Molusco', 'peixe', 'nao sei', 'pequeno', 'masculino', '2 anos', 'teste ssdssds', NULL),
(10, 'Guto', 'cachorro', 'vira-lata ', 'medio', 'masculino', '2 anos', 'bem arteiro', '1698249847680-Iron_Man_2020_Films_4K_HD_Photography_3840x2400.jpg'),
(11, 'caramelo', 'cachorro', 'vira-lata ', 'medio', 'masculino', '1 ano ', 'bem arteiro', '1698263313912-meupet.webp');  
